# Generated by Django 3.2.13 on 2022-07-03 19:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_auto_20220619_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('title',
                 models.CharField(max_length=128,
                                  verbose_name='Titre')),
                ('description',
                 models.TextField(blank=True, max_length=2048)),
                ('image',
                 models.ImageField(blank=True, null=True, upload_to='')),
                ('time_created', models.DateTimeField(auto_now=True)),
                ('has_review', models.BooleanField(default=False)),
                ('user',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('rating',
                 models.PositiveSmallIntegerField(
                     validators=[django.core.validators.MinValueValidator(0),
                                 django.core.validators.MaxValueValidator(5)],
                     verbose_name='Note')),
                ('headline',
                 models.CharField(max_length=128, verbose_name='Titre')),
                ('body',
                 models.TextField(
                     blank=True,
                     max_length=8192,
                     verbose_name='Commentaire')),
                ('time_created', models.DateTimeField(auto_now=True)),
                ('ticket',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='blog.ticket')),
                ('user',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFollows',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('followed_user',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='followed_by',
                     to=settings.AUTH_USER_MODEL)),
                ('user',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='following',
                     to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'followed_user')},
            },
        ),
    ]
